<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
$name = $block->getNameInLayout();
if($name == "sidebar.main.account.become.seller" && $block->checkSeller())
{
    return;
}
else if($name == "sidebar.main.account.seller" && !$block->checkSeller())
{
    return;
}
else {
?>
<div class="block <?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
    <div class="title <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?= /* @escapeNotVerified */ $block->getBlockCss() ?>", "selectorsToggleClass": "active"}}'>
        <strong><?= /* @escapeNotVerified */ $block->getBlockTitle() ?></strong>
    </div>
    <div class="content <?= /* @escapeNotVerified */ $block->getBlockCss() ?>-content" id="<?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
        <?= $block->getChildHtml() ?>
    </div>
</div>
<?php
}
?>