<?php
/*
 * $block = MGS\Marketplace\Block\Profile\Index
 *
 */
?>
<?php 
    $storeData = $block->getStore();
?>
<form action="<?php echo $block->getPostAction(); ?>" enctype="multipart/form-data" method="post" id="form-profile-validate" data-role="form-profile-validate" novalidate="novalidate"> 
    <?php echo $block->getBlockHtml('formkey')?>
    <div class="mgs-profile-form-content">
        <fieldset class="fieldset info mgs-marketplace-fieldset">
            <legend class="legend">
                <span>Edit Profile Information</span> 
                <button type="submit" title="Save Profile" class="button mgs-marketplace-btn right">
                    <span> 
                        <span>Save Profile</span>
                    </span>
                </button>
            </legend>
            <div class="field profile required">
                <label for="twiiter">Twitter ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="twiiter" id="twiiter" value="<?= $block->escapeHtml($storeData[0]['twiiter']) ?>" data-role="twiiter" placeholder="Twitter ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="facebook">Facebook ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="facebook" id="facebook" value="<?= $block->escapeHtml($storeData[0]['facebook']) ?>" data-role="facebook" placeholder="Facebook ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="instagram">Instagram ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="instagram" id="instagram" value="<?= $block->escapeHtml($storeData[0]['instagram']) ?>" data-role="instagram" placeholder="Instagram ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="google_plus">Google Plus ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="google_plus" id="google_plus" value="<?= $block->escapeHtml($storeData[0]['google_plus']) ?>" data-role="google_plus" placeholder="Google Plus ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="youtube">Youtube ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="youtube" id="youtube" value="<?= $block->escapeHtml($storeData[0]['youtube']) ?>" data-role="youtube" placeholder="Youtube ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="vimeo">Vimeo ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="vimeo" id="vimeo" value="<?= $block->escapeHtml($storeData[0]['vimeo']) ?>" data-role="vimeo" placeholder="Vimeo ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="pinterest">Pinterest ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="pinterest" id="pinterest" value="<?= $block->escapeHtml($storeData[0]['pinterest']) ?>" data-role="pinterest" placeholder="Pinterest ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="tax_number">Tax/VAT Number</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="tax_number" id="tax_number" data-role="tax_number" placeholder="Tax/VAT Number" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="shop_title">Shop Title</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="shop_title" id="shop_title" value="<?= $block->escapeHtml($storeData[0]['shop_title']) ?>" data-role="shop_title" placeholder="Twitter ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="shop_locality">Company Locality</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="shop_locality" id="shop_locality" value="<?= $block->escapeHtml($storeData[0]['shop_locality']) ?>" data-role="shop_locality" placeholder="Company Locality" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="shop_description">Company Description</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="shop_description" id="shop_description"><?= $block->escapeHtml($storeData[0]['shop_description']) ?></textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="return_policy">Return Policy</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="return_policy" id="return_policy"><?= $block->escapeHtml($storeData[0]['return_policy']) ?></textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="shop_policy">Shipping Policy</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="shop_policy" id="shop_policy"><?= $block->escapeHtml($storeData[0]['shop_policy']) ?></textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="meta_keywords">Meta Keywords</label>
                <label class="control-notification">(Enter Meta Keywords Comma(',') Separated..)</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="meta_keywords" id="meta_keywords"><?= $block->escapeHtml($storeData[0]['meta_keywords']) ?></textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="meta_description">Meta Description</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="meta_description" id="meta_description"><?= $block->escapeHtml($storeData[0]['meta_description']) ?></textarea>
                </div>
            </div>
        </fieldset>
    </div>
</form>
<script>
require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function(jQuery){
 
    var config = {}, 
        editor;
 
    jQuery.extend(config, {
        settings: {
            theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                        'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
            theme_advanced_buttons2: null,
            theme_advanced_buttons3: null,
            theme_advanced_buttons4: null
        }
    });
    editor = new tinyMceWysiwygSetup(
        'shop_description',
        config
    );
    editor.turnOn();
    jQuery('#shop_description')
        .addClass('wysiwyg-editor')
        .data(
            'wysiwygEditor',
            editor
        );
});
</script>