<?php
/*
 * $block = MGS\Marketplace\Block\Profile\Index
 *
 */
?>
<form action="<?php echo $block->getPostAction(); ?>" enctype="multipart/form-data" method="post" id="form-profile-validate" data-role="form-profile-validate" novalidate="novalidate"> 
    <?php echo $block->getBlockHtml('formkey')?>
    <div class="mgs-profile-form-content">
        <fieldset class="fieldset info mgs-marketplace-fieldset">
            <legend class="legend">
                <span>Edit Profile Information</span> 
                <button type="submit" title="Save Profile" class="button mgs-marketplace-btn right">
                    <span> 
                        <span>Save Profile</span>
                    </span>
                </button>
            </legend>
            <div class="field profile required">
                <label for="twitter_id">Twitter ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="twitter_id" id="twitter_id" data-role="twitter_id" placeholder="Twitter ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="facebook_id">Facebook ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="facebook_id" id="facebook_id" data-role="facebook_id" placeholder="Facebook ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="instagram_id">Instagram ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="instagram_id" id="instagram_id" data-role="instagram_id" placeholder="Instagram ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="google_plus_id">Google Plus ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="google_plus_id" id="google_plus_id" data-role="google_plus_id" placeholder="Google Plus ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="youtube_id">Youtube ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="youtube_id" id="youtube_id" data-role="youtube_id" placeholder="Youtube ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="vimeo_id">Vimeo ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="vimeo_id" id="vimeo_id" data-role="vimeo_id" placeholder="Vimeo ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="pinterst_id">Pinterest ID</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="pinterst_id" id="pinterst_id" data-role="pinterst_id" placeholder="Pinterest ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="tax_number">Tax/VAT Number</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="tax_number" id="tax_number" data-role="tax_number" placeholder="Tax/VAT Number" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="shop_title">Shop Title</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="shop_title" id="shop_title" data-role="shop_title" placeholder="Twitter ID" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="company_locality">Company Locality</label>
                <div class="control">
                    <input type="text" class="required-entry mgs-marketplace-full-width" name="company_locality" id="company_locality" data-role="company_locality" placeholder="Company Locality" aria-required="true" />
                </div>
            </div>
            <div class="field profile required">
                <label for="company_locality">Company Description</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="company_description" id="company_description">Company Description</textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="return_policy">Return Policy</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="return_policy" id="return_policy">Return Policy</textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="shipping_policy">Shipping Policy</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="shipping_policy" id="shipping_policy">Shipping Policy</textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="meta_keywords">Meta Keywords</label>
                <label class="control-notification">(Enter Meta Keywords Comma(',') Separated..)</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="meta_keywords" id="meta_keywords">Meta Keywords</textarea>
                </div>
            </div>
            <div class="field profile required">
                <label for="meta_description">Meta Description</label>
                <div class="control">
                    <textarea type="text" class="required-entry mgs-marketplace-full-width" name="meta_description" id="meta_description">Meta Description</textarea>
                </div>
            </div>
        </fieldset>
    </div>
</form>
<script>
require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function(jQuery){
 
    var config = {}, 
        editor;
 
    jQuery.extend(config, {
        settings: {
            theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                        'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
            theme_advanced_buttons2: null,
            theme_advanced_buttons3: null,
            theme_advanced_buttons4: null
        }
    });
    editor = new tinyMceWysiwygSetup(
        'company_description',
        config
    );
    editor.turnOn();
    jQuery('#company_description')
        .addClass('wysiwyg-editor')
        .data(
            'wysiwygEditor',
            editor
        );
});
</script>